### ISSUE TITLE
Interactive web-app MVP

### ISSUE THREAD

**Issue by jeetz2** [bcgov/interactive-infographic#10]
# Background
The OCIO is looking for the development of an online infographic for users to interact with. The purpose is to clearly convey multi-dimensional information in a user-friendly, interactive, digital format. 

A prototype of the online infographic was developed by @coakenfold which demonstrates basic functionality (reference  #9). The OCIO now wants to build out a minimum viable product (MVP) based on the prototype and a **recently updated** [OCIO Strategic FrameWork diagram](https://github.com/bcgov/interactive-infographic/blob/master/wireframe/ocio_framework_2016%20v4.pdf).

See the [Readme](https://github.com/bcgov/interactive-infographic/blob/master/README.md) for more info.

### Story
As a product owner, I want to be able to create an MVP of an interactive infographic web-app so that that I can circulate it among my government colleagues for feedback.

## Acceptance Criteria

1. Develop a MVP of a dynamic version of the [OCIO Strategic FrameWork diagram](https://github.com/bcgov/interactive-infographic/blob/master/wireframe/ocio_framework_2016%20v4.pdf). See this [wireframe](https://github.com/bcgov/interactive-infographic/blob/master/wireframe/wireframe.png) that illustrates how the interactive infographic might be structured. The MVP should make all of the relevant elements in the diagram interactive (e.g. bootstrap jQuery plugins: accordion, popovers, video, etc...). The MVP should also be made aesthetically appealing and visually similar to the latest diagram provided. Some exceptions are expected and the developer should communicate any recommended changes that would improve the online experience (e.g. the developer can ignore/remove the 3 vertical columns on the left side of the diagram). Dummy text content can be used where required and government staff can update the content after the issue is closed.

The following acceptance criteria from the previous issue (#2) remain applicable:
2. Allow the insertion and deletion of content boxes (i.e. rows, see [wireframe](https://github.com/bcgov/interactive-infographic/blob/master/wireframe/wireframe.png)).
3. Allow the insertion and deletion of content elements (i.e. see [wireframe](https://github.com/bcgov/interactive-infographic/blob/master/wireframe/wireframe.png)).
4. Content box should have the ability to contain multiple content elements that scale according to the number of content elements. 
5. Allow the insertion and deletion of graphics (and perhaps text) into the content elements.
6. When a user clicks on a content element (every row, or content box, should have this capability), an accordion window will expand/appear underneath. This [second diagram](https://github.com/bcgov/interactive-infographic/blob/master/wireframe/user-interaction.png) illustrates how a user might interact with the infographic.
7. Allow the insertion and deletion of content in accordion windows, including text and hyperlinks (possibly graphics).
8. Support vector graphics. You can use example graphics and text for the prototype.
9. Provide the final product in a format that can be run on any computer (localhost) through any modern web-browser.
10. Device agnostic and responsive.
11. Use of commonly known, open web frameworks.

## How to contribute

We will evaluate each pull request and choose the best solution to the issue based on the acceptance criteria. Submit the best solution and you could be paid $1000.

More than one pull request may be considered for payment on this issue.

Please read the [Contribution Guidelines](https://github.com/bcgov/interactive-infographic/blob/master/CONTRIBUTING.md) for the Terms that set the rules for participation in a Pay for Pull, including how you’ll get paid if you are successful.

Have questions? Please post your questions in the comments section below this issue.

And check out our [Partners page](https://bcdevexchange.org/programs/OCIO%20Tech%20Strategies)  for more information on our work.

**Comment by Filoni** [comment]
I'd be happy to lend a hand on this, @jeetz2 let me know if I can get started!

**Comment by jeetz2** [comment]
@Filoni great and please feel free to get started. Just like the last issue, could any others who are interested in contributing wait for the first developer that responds to take a stab at meeting the criteria. Tkx.

**Comment by coakenfold** [comment]
Sounds good @jeetz2. Put me down for next in line if the opportunity arises.

**Comment by jeetz2** [comment]
Ok @coakenfold will certainly do

**Comment by robertmartinbc** [comment]
Hi, I'm tryin to ascertain if this project is actually being worked on at the moment? I see a number of commits some days ago but just wandering what the status was? Thanks.

**Comment by Filoni** [comment]
Currently working on it, should have a pull request good to go this weekend. Work has just been hectic!

**Comment by robertmartinbc** [comment]
Okay. Thanks for the update.

**Comment by jeetz2** [comment]
Hi @Filoni , thanks for the submission and it met the acceptance criteria. Stay tuned everyone - we will publish another issue soon with feature requests. Jitu
