### ISSUE TITLE
web-app hosting

### ISSUE THREAD

**Issue by jeetz2** [bcgov/interactive-infographic#12]
# Background

Once this project is complete, it will need to be hosted somewhere.

# Criteria

Hi @kelpisland we need to start getting the hosting environment setup:

1. Hosting environment should be stable and reliable for and post-launch
2. Must be hosted in Canada
3. Must be able to change from Government Intranet to Internet and vice-versa, if needed
4. Must support the web development platforms/stacks used by the developers (see the code submitted in #9 and #11 )
5. URL:  OCIOstrategyframework.gov.bc.ca or similar

**Comment by kelpisland** [comment]
Hey @jeetz2  - I've added a ticket to the "Code 4 Gov" epic backlog for setting up an OpenShift project space for the OCIO Interactive Infographic. As soon as we have the project space we can get a DNS and build process set up. ETA, Sept 21

**Comment by jeetz2** [comment]
Thanks @kelpisland . The launch date is October 4th, so it would be good to have it up and running a week before hand.

**Comment by jeetz2** [comment]
@kelpisland  and @sheaphillips the OpenShift environment is so convenient. Love the push button build and deploys. Can wait for a dev/uat env too. 

Thanks agian, and I'm closing this issue.
