### ISSUE TITLE
Interactive web-app launch-ready

### ISSUE THREAD

**Issue by jeetz2** [bcgov/interactive-infographic#13]
# Background
The OCIO is looking for the development of an online infographic for users to interact with. The purpose is to clearly convey multi-dimensional information in a user-friendly, interactive, digital format. 

A prototype of the online infographic was developed by @coakenfold which demonstrates basic functionality (reference  #9) and a minimum viable product (MVP) based on the prototype was built by @Filoni (reference #10 ).

**The next step is to prepare the online framework for launch.** This means getting a fully functional strategic framework (see [latest update](https://github.com/bcgov/interactive-infographic/blob/master/wireframe/OCIO%20Strategic%20Framework%20v10.pdf) to OCIO Strategic Framework Diagram) complete with graphics and begin populating the content in each section. There will likely be one additional pull request after this one to work with OCIO staff to populate all of the content within the framework, design clean-up, final functionality, etc...

See the [Readme](https://github.com/bcgov/interactive-infographic/blob/master/README.md) for more info.

### Story
As a product owner, I want to be able to create a launch-ready interactive infographic web-app to be published for users.

## Acceptance Criteria

1. Develop a launch-ready online version of the [OCIO Strategic FrameWork diagram](https://github.com/bcgov/interactive-infographic/blob/master/wireframe/OCIO%20Strategic%20Framework%20v10.pdf). The interactive-infographic should replicate as closely as possible the provided diagram, and all of the relevant elements in the diagram should be interactive, and content can begin to get populated.
2. The interactive-infographic will be tested by a few users, and should provide them with a satisfactory and intuitive user experience
3. Acceptance criteria 2 to 11 from the last issue (#10) remain applicable.

## How to contribute

We will evaluate each pull request and choose the best solution to the issue based on the acceptance criteria. Submit the best solution and you could be paid $1000.

More than one pull request may be considered for payment on this issue.

Please read the [Contribution Guidelines](https://github.com/bcgov/interactive-infographic/blob/master/CONTRIBUTING.md) for the Terms that set the rules for participation in a Pay for Pull, including how you’ll get paid if you are successful.

Have questions? Please post your questions in the comments section below this issue.

And check out our [Partners page](https://bcdevexchange.org/programs/OCIO%20Tech%20Strategies)  for more information on our work.

**Comment by Filoni** [comment]
Happy to help as I did before :)

**Comment by coakenfold** [comment]
I'm interested as well.

**Comment by jeetz2** [comment]
Hi guys. @Filoni why don't you take the first stab at this, building on the MVP. @coakenfold stay tuned for next issue or if @Filoni needs help with this one
