### ISSUE TITLE
Interactive web-app complete

### ISSUE THREAD

**Issue by jeetz2** [bcgov/interactive-infographic#15]
# Background
Issue #13 was not properly scoped in order to complete the development of the online infographic. Effort for development was greater than originally estimated. To meet the tight deadlines of the OCIO, this fourth issue has been created so that the development work could be completed and the site launched.

The intention is that the developer for Issue #13 can complete the work.

See the [Readme](https://github.com/bcgov/interactive-infographic/blob/master/README.md) for more info.

## Acceptance Criteria

1. Develop a launch-ready online version of the OCIO Strategic FrameWork diagram. All content populated, design complete, functionality and user testing complete.
2. Acceptance criteria 2 to 11 from the last issue remain applicable.

## How to contribute

We will evaluate each pull request and choose the best solution to the issue based on the acceptance criteria. Submit the best solution and you could be paid $1000.

More than one pull request may be considered for payment on this issue.

Please read the [Contribution Guidelines](https://github.com/bcgov/interactive-infographic/blob/master/CONTRIBUTING.md) for the Terms that set the rules for participation in a Pay for Pull, including how you’ll get paid if you are successful.

Have questions? Please post your questions in the comments section below this issue.

And check out our [Partners page](https://bcdevexchange.org/programs/OCIO%20Tech%20Strategies)  for more information on our work.

**Comment by Filoni** [comment]
Thanks for setting this up Jitu! Happy to help finish this off :)

**Comment by coakenfold** [comment]
Is this an open issue for everyone or is it meant specifically for @Filoni?

**Comment by jeetz2** [comment]
@Coakenfold - I undervalued the work necessary on this issue, that was completed by @Filoni. I want to pay a fair price for the additional work, so I would like to request @Filoni gets the first crack to tie up the lose ends before I demo the app tomorrow. That being said, anyone is welcome to submit a solution for this issue. 

This new model is still an experiment so I expect there is some things to learn here.
