### ISSUE TITLE
Interactive web app prototype

### ISSUE THREAD

**Issue by lmullane** [bcgov/interactive-infographic#2]
# Background
The OCIO is looking for the development of an online infographic for users to interact with. The purpose is to clearly convey multi-dimensional information in a user-friendly, interactive, digital format. 

The work entails the development of a working prototype of a dynamic version of the [OCIO Strategic FrameWork diagram](https://raw.githubusercontent.com/bcgov/interactive-infographic/master/wireframe/OCIO_Strategy_Framework.png). The prototype must enable the layout and content to change as the strategy may change over time. 

See the [Readme](https://github.com/bcgov/interactive-infographic/blob/master/README.md) for more info.

### Story
As a product owner, I want to be able to create a working prototype of an interactive web-app so that that I can improve the experience and understanding of government strategy by using a visual, interactive digital format.

## Acceptance Criteria

1. Develop a working prototype of a dynamic version of the [OCIO Strategic FrameWork diagram](https://raw.githubusercontent.com/bcgov/interactive-infographic/master/wireframe/OCIO_Strategy_Framework.png). See this [wireframe](https://github.com/bcgov/interactive-infographic/blob/master/wireframe/wireframe.png) that illustrates how the interactive infographic might be structured.
2. Allow the insertion and deletion of content boxes (i.e. rows, see [wireframe](https://github.com/bcgov/interactive-infographic/blob/master/wireframe/wireframe.png)).
3. Allow the insertion and deletion of content elements (i.e. see [wireframe](https://github.com/bcgov/interactive-infographic/blob/master/wireframe/wireframe.png)).
4. Content box should have the ability to contain multiple content elements that scale according to the number of content elements. Challenge us on this one if it's unrealistic.
5. Allow the insertion and deletion of graphics (and perhaps text) into the content elements.
6. When a user clicks on a content element (every row, or content box, should have this capability), an accordion window will expand/appear underneath. This [second diagram](https://github.com/bcgov/interactive-infographic/blob/master/wireframe/user-interaction.png) illustrates how a user might interact with the infographic.
7. Allow the insertion and deletion of content in accordion windows, including text and hyperlinks (possibly graphics).
8. Support vector graphics. You can use example graphics and text for the prototype.
9. Provide the final product in a format that can be run on any computer (localhost) through any modern web-browser.
10. Device agnostic and responsive.
11. Use of commonly known, open web frameworks.

## How to contribute

We will evaluate each pull request and choose the best solution to the issue based on the acceptance criteria. Submit the best solution and you could be paid $1000.

More than one pull request may be considered for payment on this issue.

Please read the [Contribution Guidelines](https://github.com/bcgov/interactive-infographic/blob/master/CONTRIBUTING.md) for the Terms that set the rules for participation in a Pay for Pull, including how you’ll get paid if you are successful.

Have questions? Please post your questions in the comments section below this issue.

And check out our [Partners page](https://bcdevexchange.org/programs/OCIO%20Tech%20Strategies)  for more information on our work.

**Comment by lmullane** [comment]
Hi, @kelpisland and I are the technical contacts for this issue. If you have questions, please post a comment here so everyone can participate in the conversation.

**Comment by lmullane** [comment]
Q: Should I let people know I am working on this issue?
A: It would be great if you would comment in this thread to let others know you intend to work on this issue.

**Comment by sevenlayerdip** [comment]
Are the tech labels suggestions or requirements?

**Comment by lmullane** [comment]
No, the labels are not requirements - they capture the skills we think are needed. But the what is delivered will be compared to the acceptance criteria in the issue, which are pretty broad currently.

**Comment by coakenfold** [comment]
Hello, I would like to help out with this issue but I'm not clear on the scope & deliverables. 

Is it solely wireframe/UX planning & collaboration? 
> The first work (i.e. issue) will be to collaborate and validate the wireframe and user interaction diagram. Determine the suitable approach to developing a flexible infographic structure/framework/navigation that can be easily modified after development.

via [Readme](https://github.com/bcgov/interactive-infographic/blob/master/README.md#user-content-what)

Or does it include development? 
> Ensure that the “content boxes (see wireframe)” can be resized vertically or horizontally, reordered, new content boxes can be added or existing ones removed, graphics, videos and text can be replaced, and additional “content elements” can added to a “content box” or existing ones removed. 

> Once the suitable approach is agreed on, the next work (i.e. issue) will be to develop a working prototype.

via [Readme](https://github.com/bcgov/interactive-infographic/blob/master/README.md#design)

**Comment by lmullane** [comment]
Great questions, @coakenfold. This issue is UX. This includes wireframes with more than one design option and a plans for the prototype. There would be a second Pay for Pull issue to code the design into a prototype. 

Let me know if that answers your question?

**Comment by stephenrichter** [comment]
Hi @lmullane, I'm not sure how much detail you can give on the intended content.

> The purpose is to clearly convey multi-dimensional information in a user-friendly, interactive, digital format.

Can we assume this "multi-dimensional information" would be something like a Strategic Plan, as it is in the example provided? (http://www.healthcarevaluehub.org/improving-value/interactive_strategies/).

If so, I'd like to get involved in this. Are the next steps to begin development/validation of the wireframe and UX indepdently or get connected with the product owner or you, as the technical contact?

**Comment by lmullane** [comment]
Hi @stephenrichter, yes the thinking is it would be similar to the example you provided.

Given that this issue is mainly focused on design we think there's value in taking the collaborative approach. Part of our interest in this issue is to experiment and see if we can find a way to tackle design issues as a Pay for Pull.

So we are thinking of hosting a discovery session for those interested in contributing. Anyone who wants to attend could do so.

@stephenrichter @coakenfold @sevenlayerdip would you be interested in participating in a discovery session?

**Comment by coakenfold** [comment]
Thanks for the invitation @lmullane. I've been thinking about this issue and I'm more interested in helping out during the build phase.

I think the challenges of multiple parties collaborating on design related issues (under spec) would be minimized with fewer 'cooks in the kitchen.'

I'm happy to provide technical feedback on proposed features if that's of any assistance.

**Comment by lmullane** [comment]
Hi @coakenfold, thanks for your speedy reply. We will gauge the interest of others on the discovery day approach and keep you informed here.

Btw, we are working to address the spec work issue. So stay tuned.

**Comment by stephenrichter** [comment]
@lmullane I think it's an interesting experiment.. I'd be happy to work through a discovery session.

@coakenfold I'm open to collaborating on the build phase or a 'passing of the baton' depending on the proposed technologies and features from the design phase. Just thinking out loud...

**Comment by lmullane** [comment]
Great. I will connect with @kelpisland and we will circle back on possible times.

**Comment by lmullane** [comment]
@stephenrichter What's your calendar looking like for Monday to Wednesday next week? @m-a-wilson

**Comment by lmullane** [comment]
Hi all, 

We have modified the acceptance criteria for this issue to provide more detail on what we would like. Rather than focus on design we are asking for those interested to develop a working prototype. 

We laid out our desired prototype functionality in the updated acceptance criteria. We welcome your feedback and questions.

@jeetz2 is the program owner (recently returned from time off) and is keen to answer any questions you may have.

@stephenrichter @coakenfold @sevenlayerdip

**Comment by coakenfold** [comment]
Hello, 

I did some work on this issue. What I've worked on seems to meet the acceptance criteria but I would appreciate some feedback before submitting a pull request. 

It's hard to tell how far to take the UI/UX since this is a prototype.

The forked repo is here: 
https://github.com/coakenfold/interactive-infographic

I've committed a built version of the files which sidesteps the need to run 'npm install' and 'grunt': 
https://github.com/coakenfold/interactive-infographic/tree/master/code/interactiveWebAppPrototype/build

Thanks

**Comment by lmullane** [comment]
@coakenfold We will take a look and get back to you. @jeetz2

**Comment by Filoni** [comment]
@lmullane @jeetz2 This looks like a very interesting issue, and I'd love to work on a prototype. Let me know if this opportunity is still open to contributions.

**Comment by coakenfold** [comment]
Made some updates to the prototype: 
* using modals with the 'youtube' and 'about the ocio' buttons in the top row
* youtube scripting for video start/stop
* inline svg of the youtube logo (instead of `<img src='some.svg'>`).

In my repo:
https://github.com/coakenfold/interactive-infographic/tree/master/code/interactiveWebAppPrototype/build

And online:
http://oakenfold.ca/bcdev/ocio-prototype/

Let me know if I should be submitting pull requests instead of these updates via the comments.

**Comment by lmullane** [comment]
@coakenfold Yes, please submit a PR.

**Comment by jeetz2** [comment]
@coakenfold Hi Chad, we're just reviewing the acceptance criteria  @Filoni thanks for letting us know you're interested. Out of consideration to Chad it would be ideal to hold off on any contributions for the moment.

**Comment by lmullane** [comment]
We have merged a [PR](https://github.com/bcgov/interactive-infographic/pull/9#issuecomment-234322842 ) for this issue. Thanks for your work, @coakenfold

**Comment by coakenfold** [comment]
Thank you for accepting the pull request. Please contact me if you have any unanswered questions.

**Comment by jeetz2** [comment]
This was my first pay for pull experience, it was great to see this level of engagement. I'm looking forward to moving this project along. I'm interested in soliciting some of your ideas for where this could go. If you have any potential features that you think would enhance the functionality of the prototype, feel free to open an issue and we may turn some of them into more pay for pulls. Some ideas that have come to my mind: easier content editing (e.g. drag-and-drop/edit in place) for non-developers; preview functionality; other bootstrap elements; etc... Thanks!
